### ISSUE TITLE
Need to re-login into Google account once the app is closed

### ISSUE THREAD

**Issue by emer7** [CS2103JAN2018-W15-B1/main#98]
Is this intended?

**Comment by crizyli** [comment]
Well, I think we need to turn those calendars to Public to All manually in google calendar website, because there seems no such api to turn a calendar to public.
Otherwise, we need some kind of cache to store the login information, but I don't know how to achieve that.

**Comment by emer7** [comment]
We cannot create a public calendar from the beginning using the API?

Or how if we use cookie / session? Would that be feasible?
